[package]
name = "rust_os"
version = "0.1.0"
authors = ["wy <wangy10@chinatelecom.cn>"]
edition = "2018"

[dependencies]
bootloader = "*"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
